default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fakebook_app_sample_development

test:
  <<: *default
  database: fakebook_app_sample_test

production:
  <<: *default
  database: fakebook_app_sample_production
  username: fakebook_app_sample
  password: <%= ENV['FAKEBOOK_APP_SAMPLE_DATABASE_PASSWORD'] %>
